### PR TITLE
Add possibility to ping via email, Closes #55

### LINKED ISSUE #55: Feature Request: Support Receiving Email Pings
Healthchecks application is designed to also accept email pings as well as http pings, but the container needs to be configured to listen for SMTP requests.

Official docs on it: https://github.com/healthchecks/healthchecks#receiving-emails

------------------------------

## Expected Behavior

Container supports environment variable to enabling and configuring SMTPd in the container for SMTP Pings

## Current Behavior

There is no support for SMTPd or SMTP Pings

## Environment

**OS:**      Ubuntu 18.04
**CPU architecture:** x86_64
**How docker service was installed:**      apt repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  healthchecks:
    image: linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT={REDACTED}
      - SITE_NAME={REDACTED}
      - DEFAULT_FROM_EMAIL={REDACTED}
      - EMAIL_HOST=192.168.1.28
      - EMAIL_PORT=2525
      - EMAIL_HOST_USER={REDACTED}
      - EMAIL_HOST_PASSWORD={REDACTED}
      - EMAIL_USE_TLS=False
      - SUPERUSER_EMAIL={REDACTED}
      - SUPERUSER_PASSWORD={REDACTED}
      - DOCKER_MODS=linuxserver/mods:healthchecks-apprise
      - SERVICE_TAGS=traefik.frontend.redirect.entryPoint=https,traefik.frontends.int.rule=Host:{{.ServiceName}}.int.{{.Domain}},traefik.frontends.ext.rule=Host:hc.{{.Domain}},traefik.frontend.headers.SSLRedirect=true,traefik.frontend.passHostHeader=true
      - SERVICE_NAME=healthchecks
    volumes:
      - ./config:/config
    ports:
      - 8000:8000
    restart: unless-stopped
```

### PR DESCRIPTION
**Pull request by xontik**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-healthchecks/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Added launch script to start an smtpd server to handle incomming mail ping

## Benefits of this PR and context:

Closes #55 

## How Has This Been Tested?

i tried to send mail and mail are working !

## Source / References:

[Original project doc on how to receive mail](https://github.com/healthchecks/healthchecks#receiving-emails)

### CODE REVIEW

**Comment by xontik** [comment]
Can some one take a look at this ?

**Comment by xontik** [comment]
Well if no one car at least close this pr i wont update it to then wait 6 month for someone to look at it

**Comment by Openhabber** [comment]
Is this container not maintained anymore?

**Comment by xontik** [comment]
I still use it ! Works fine but maintainers ghosted me :p

**Comment by toxsick** [comment]
Hey there, I need this too and @xontik seems to have done the work here. Thanks for this BTW. Can anybody review this?

Thanks you guys!!

**Comment by Openhabber** [comment]
@alex-phillips can you merge the two PRs? Would be really happy :) Thanks!

**Pull request closed without merging**
