### PR TITLE
Add SECRET_KEY to env documentation

### PR DESCRIPTION
**Pull request by dudeofawesome**
------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-healthchecks/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description & Benefits of this PR and context:

The official Healthchecks image says to [include a `SECRET_KEY` env var](https://github.com/healthchecks/healthchecks/tree/master/docker), but this image doesn't, which leads to a banner at the top of the page saying "Running with an insecure SECRET_KEY value, do not use in production."
Simply adding the env var gets rid of this message in the current linuxserver image, so I figured it would be good to document it.

## How Has This Been Tested?

I'm using `SECRET_KEY` on my container.

## Source / References:

https://github.com/healthchecks/healthchecks/tree/master/docker

### CODE REVIEW

**Comment by aptalca** [comment]
Wouldn't it be better to generate one during init and store in the config folder?

**Comment by dudeofawesome** [comment]
Yeah, that would make a lot of sense. I was just copying what they've done in the official image.

**Comment by chasebolt** [comment]
this looks good to merge in

**Comment by chasebolt** [comment]
> Wouldn't it be better to generate one during init and store in the config folder?

if this was stored in the config then this app becomes stateful, versus currently we are able to run it stateless in k8s.

**Comment by aptalca** [comment]
Then have the env var override any stored value. But if there is no env var, use the stored one, and generate if needed. Best of both worlds.

**Comment by chasebolt** [comment]
you should definitely add that! or else have it in a different PR so this
can move forward.

**Comment by dudeofawesome** [comment]
Can a maintainer take a look at this? I believe this change is still relevant, and it's just extra documentation.

**Comment by Roxedus** [comment]
We have, and came with some feedback on wanted changes

**Comment by dudeofawesome** [comment]
Ah! I missed that those behavioral changes were wanted in this PR.

I'm not really familiar with the structure of LSIO images. Would the appropriate way to handle this be to create a `/config/secret_key` file at runtime?

**Comment by Roxedus** [comment]
That would be a good place to have it, yea.

**Pull request closed without merging**
