### PR TITLE
Allow to create superuser

### PR DESCRIPTION
**Pull request by lukasmrtvy**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:

Allow to create superuser

## Benefits of this PR and context:

Allow to create superuser

## How Has This Been Tested?

code,build,run,test

## Source / References:

none

### CODE REVIEW

**Comment by alex-phillips** [comment]
@lukasmrtvy It appears to work - any way to suppress the python error that's thrown? Possibly an `except` statement?

```
Check if user already exists. 
Traceback (most recent call last):
  File "/app/healthchecks/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 92, in handle
    exec(sys.stdin.read())
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Creating superuser. 
Superuser created.
```

**Comment by lukasmrtvy** [comment]
@alex-phillips I can send output to /dev/null, but its good for debugging..  ( I dont like it either :)

**Comment by lukasmrtvy** [comment]
@alex-phillips 
Is this https://stackoverflow.com/a/41577137/3797368 enough ?

**Comment by alex-phillips** [comment]
That would be much cleaner! Commit that change and I can test it.

**Comment by lukasmrtvy** [comment]
@alex-phillips its updated

**Comment by alex-phillips** [comment]
LGTM. Thanks!

**Pull request merged**
