### PR TITLE
Install Apprise as project dependency (introduced in v1.24.0)

### PR DESCRIPTION
**Pull request by immanuelfodor**
Install Apprise as project dependency in parallel with https://github.com/healthchecks/healthchecks/issues/581 and https://github.com/healthchecks/healthchecks/commit/b77c54f6655a29f648576e5d5fff341d00576c04 that was released in https://github.com/healthchecks/healthchecks/releases/tag/v1.24.0

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-healthchecks/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Healthcheck's Apprise integration depends on the `apprise` pip package, and it's now included in the upstream Dockerfile by default. This change was introduced in v1.24.0, this PR keeps the LS image in parallel with it. Also added the relevant upstream environment variable to the readme (not used in the Dockerfile but consumed by the `settings.py`).

## Benefits of this PR and context:
Apprise integration can now be used without dirty runtime hacks or custom built dockerfiles.

## How Has This Been Tested?

Ran the docker build command on Ubuntu, the pip install was fine.

## Source / References:

- Original issue: https://github.com/healthchecks/healthchecks/issues/581
- Fixed in commit: https://github.com/healthchecks/healthchecks/commit/b77c54f6655a29f648576e5d5fff341d00576c04
- Released in v1.24.0: https://github.com/healthchecks/healthchecks/releases/tag/v1.24.0
- Env var reference: https://healthchecks.io/docs/self_hosted_configuration/

### CODE REVIEW

**Comment by immanuelfodor** [comment]
Who has permission to merge this PR? Maybe gently nudging @alex-phillips helps? :)

**Comment by immanuelfodor** [comment]
Hellooo, anyone?

**Comment by immanuelfodor** [comment]
How should I get this merged? 😃

**Comment by TheSpad** [comment]
Can you update the readme as it now has a merge conflict with https://github.com/linuxserver/docker-healthchecks/pull/84

**Comment by immanuelfodor** [comment]
Of course, done

**Pull request merged**
